In [12]:
#Exercise 1
import numpy as np
from scipy import linalg as LA

#a)
'''
           A     *    v     =   b
     [4 -1 -1 0 0]   [V1]      [5]
     [-1 4 -1 0 0]   [V2]      [5]
     [-1 -1 4 -1 -1] [V_i]     [0]
     [0 0 -1 3 -1]   [V_N-1]   [0]
     [0 0 -1 -1 3]   [V_N]     [0]
'''

#b)
A = np.array(([4, -1, -1, 0, 0], 
              [-1, 4, -1, 0, 0], 
              [-1, -1, 4, -1, -1], 
              [0, 0, -1, 3, -1], 
              [0, 0, -1, -1, 3]))

b = np.array(([5, 5, 0, 0, 0]))

N = 4

for i in range(0, N, 2):
    v = LA.solve(A, b)
print('\nA\n', A, '\nb\n', b, '\nv\n', v)




A
 [[ 4 -1 -1  0  0]
 [-1  4 -1  0  0]
 [-1 -1  4 -1 -1]
 [ 0  0 -1  3 -1]
 [ 0  0 -1 -1  3]] 
b
 [5 5 0 0 0] 
v
 [2.14285714 2.14285714 1.42857143 0.71428571 0.71428571]


In [3]:
#Exercise 2
import numpy as np
from scipy import linalg as LA
from numpy import linalg as npl
#a) The rank of the matrix is 2 because two of the rows are linearly independent
# This means that the dimension of the nullspace is ...
A = np.array([[2, 4, 6, 8], 
              [-1, 0, 1, 0], 
              [1, 2, 3, 4], 
              [1, 4, 7, 8]])

p, l, u = LA.lu(A)
print('a)\n Permutation Matrix (p)\n', p, 
    '\nLower Diagonal (l)\n', l, 
     '\nUpper Diagonal(u)\n', u)

#b)
eigvals, eigvects = LA.eig(A)
print('Eigenvalues\n', eigvals)

#c) The last two singular values are equal to zero
U, s, Vh = LA.svd(A)
print('Unitary Matrix 1 (U)\n', U,
     '\nSingular Values (s)\n', s,
     '\nUnitary Matrix 2 (Vh)\n', Vh)

#d)
m, n = 4, 4
S = np.zeros((m, n))
for i in range(min(m, n)):
    S[i, i] = s[i]
print('S\n', S)

U = npl.inv(U)
Vh = npl.inv(Vh)

b = np.array([12, 0, 6, 12])


new_A = npl.multi_dot((U, Vh, S))
print('new A\n', new_A)
x, R, r, S_new_A = LA.lstsq(new_A, b)
print('Least Squares Solution\n', x, '\nResidues\n', R, '\nrank\n', r, '\nSingular Values of new A\n', S_new_A)

a)
 Permutation Matrix (p)
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 
Lower Diagonal (l)
 [[ 1.   0.   0.   0. ]
 [-0.5  1.   0.   0. ]
 [ 0.5  0.   1.   0. ]
 [ 0.5  1.   0.   1. ]] 
Upper Diagonal(u)
 [[2. 4. 6. 8.]
 [0. 2. 4. 4.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Eigenvalues
 [ 1.25207973e+01+0.j  4.79202711e-01+0.j -5.49147729e-16+0.j
 -3.27845630e-15+0.j]
Unitary Matrix 1 (U)
 [[-0.65450214  0.37822681  0.61028199 -0.23691205]
 [-0.02654771 -0.8013441   0.25911404 -0.53851905]
 [-0.32725107  0.1891134  -0.7023359  -0.60321401]
 [-0.68104985 -0.42311729 -0.25911404  0.53851905]] 
Singular Values (s)
 [1.67090363e+01 1.67573997e+00 3.15135948e-16 6.79421900e-17] 
Unitary Matrix 2 (Vh)
 [[-0.13709692 -0.35889024 -0.58068356 -0.71778049]
 [ 0.78997568  0.11855352 -0.55286865  0.23710703]
 [-0.5916123   0.3630907  -0.5916123   0.41006695]
 [-0.08448514 -0.85165016 -0.08448514  0.51031022]]
S
 [[1.67090363e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+