In [2]:
#Exercise 2
from scipy import linalg as LA
import numpy as np

#a)
A = np.array([[1, 2, 3], [3, 8, 7], [2, 0, 7]])

p, L, U = LA.lu(A)

print('a)', 'Permutation Matrix \n', p, '\n', '\nLower Diagonal Matrix \n', L, '\n', '\nUpper Diagonal Matrix \n', U, '\n')

#b) I think U and L are different from the pen and paper version because scipy uses pivots while we did not use pivots
#for calculating U and L. 


#c) 
b = np.array([1, 3, 2])

x = LA.solve(A, b)

print('b)', 'A solved for b\n', x)


a) Permutation Matrix 
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]] 
 
Lower Diagonal Matrix 
 [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.125      1.        ]] 
 
Upper Diagonal Matrix 
 [[ 3.          8.          7.        ]
 [ 0.         -5.33333333  2.33333333]
 [ 0.          0.          0.375     ]] 

b) A solved for b
 [ 1. -0.  0.]


In [30]:
#Exercise 3
import numpy as np
from scipy import linalg as LA
#a)
'''
4V2 - V4 - V3 - V1 = V+
3V1 - V3 - V2 = V+
4V3 - V4 - V2 - V1 = V0
3V4 - V3 - V2 = V0
'''
#b)
'''
           A         v     =   b
     [-1 4 -1 -1]   [V1]      [5]
     [3 -1 -1 0]    [V2]      [5]
     [-1 -1 4 -1] * [V3]      [0]
     [0 -1 -1 3]    [V4]      [0]
'''
A = np.array([[-1, 4, -1, -1], 
              [3, -1, -1, 0], 
              [-1, -1, 4, -1], 
              [0, -1, -1, 3]])

b = np.array([5, 5, 0, 0])

#c)
V = LA.solve(A, b)

print('Voltages\n', np.reshape(V, (4, 1)))



Voltages
 [[3.33333333]
 [3.        ]
 [2.        ]
 [1.66666667]]
